### ISSUE TITLE
Not showing the effect within relative positioned element.

### ISSUE THREAD

**Issue by ismailrubad** [geosenna/simpleParallax#3]
It works fine but when the image is a child element of a relative parent then it breaks. Can you help me?

**Comment by geosenna** [comment]
Hi ismailrubad,

Could you please share a codepen to see the issue? I can't reproduce it, it is working fine with a relative parent container.

**Comment by alvinseliang** [comment]
Me too, if i place the img tag inside div that have position:relative, parallax stop working.

**Comment by geosenna** [comment]
Yes I get the idea, but I can't reproduce it. Could you share a demo or something so I can see what is happening?

**Comment by alvinseliang** [comment]
Please try wrap your <img class=thumbnail ... > inside

and parallax won’t work
Because w3-container has position: relative

**Comment by geosenna** [comment]
https://codepen.io/anon/pen/PdrNoy

**Comment by geosenna** [comment]
I'm glad that fit you.
