### ISSUE TITLE
Place text on top parallax image

### ISSUE THREAD

**Issue by alvinseliang** [geosenna/simpleParallax#4]
How to add or place text on top center the image?

**Comment by alvinseliang** [comment]
Please try wrap your <img class=thumbnail ... > inside <div class=w3-container> and parallax won’t work

Because w3-container has position: relative

**Comment by alvinseliang** [comment]
I want place your parallax image inside a div container and place multi text or div on top your parallax img

<div class=container style=position: relative>
<img class=thumbnail ...>
<div class=...> some text </div>
</div

I tried above and parallax wont work

**Comment by geosenna** [comment]
https://codepen.io/anon/pen/PdrNoy

**Comment by alvinseliang** [comment]
I checked your codepen.. if i change to other parallax effect like orientation.. your parallax cannot work..

**Comment by geosenna** [comment]
The wrong cdn version was loaded.. I updated the readme and the codepen. It should work fine now.

**Comment by geosenna** [comment]
The offset is miscalculated because of this relative parent indeed. I'll take a look.

**Comment by alvinseliang** [comment]
Thanks.. will wait for your update soon!

**Comment by geosenna** [comment]
https://github.com/geosenna/simpleParallax/releases/tag/3.1.1

**Comment by alvinseliang** [comment]
Hi! Have you updated your codepen too?

**Comment by geosenna** [comment]
yes

**Comment by geosenna** [comment]
I close this ticket, as I assume the issue has been fixed.
