### ISSUE TITLE
Minified v3.1.1 missing code

### ISSUE THREAD

**Issue by mallow76** [geosenna/simpleParallax#5]
The beginning part of the code in the minified version of 3.1.1 is missing (from CDN and dist in download).

**Comment by geosenna** [comment]
Hey, sorry about that.

The correct version has been put in the [3.1.2 release ](https://github.com/geosenna/simpleParallax/releases/tag/3.1.2)

**Comment by mallow76** [comment]
Still looks like the same issue is there...
