### ISSUE TITLE
Still looks like the same issue with minified code is there...

### ISSUE THREAD

**Issue by mallow76** [geosenna/simpleParallax#6]
Or at least there is some kind of issue with the beginning of the code.

_Originally posted by @mallow76 in https://github.com/geosenna/simpleParallax/issues/5#issuecomment-427680161_

**Comment by geosenna** [comment]
check out [3.1.3](https://github.com/geosenna/simpleParallax/releases/tag/3.1.3) and let me know

**Comment by mallow76** [comment]
Yes - fixed now. Thanks

**Comment by mallow76** [comment]
And same issue again now with minified version in dist v4.0.0...

**Comment by geosenna** [comment]
https://github.com/geosenna/simpleParallax/releases/tag/4.0.1

let me know.

**Comment by mallow76** [comment]
No change. Minified code starts at "use strict".

**Comment by geosenna** [comment]
Could you share a codepen or something so I can see the issue? Do you have an error in the console?
