### ISSUE TITLE
SimpleParallax.destory() unreachable?

### ISSUE THREAD

**Issue by justintaddei** [geosenna/simpleParallax#8]
I'm building a SPA with your module and need to clear the instance when the route changes to avoid a memory leak. However, the `destory` method is not reachable from the users code.

```javascript
const parallax = new SimpleParallax(img)

console.log(parallax)
// `{ }`

parallax.destroy()
// Uncaught TypeError: parallax.destory is not a function
```

I believe the issue is due to `handle` returning `undefined`

```javascript
// simpleParallax.js:71
function handle(element, options) {
    if (element.length) {
        for (var i = 0; i < element.length; i++) { 
            new SimpleParallax(element[i], options);
        }
    } else {
        new SimpleParallax(element, options);
    }
}
```

I am more than happy to create a PR for this issue.

**Comment by geosenna** [comment]
fixed with https://github.com/geosenna/simpleParallax/pull/9
